services:
  front-office:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3030:3030
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app